wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.13.5
    framework: catboost
    huggingface_version: 4.23.1
    is_jupyter_run: false
    is_kaggle_kernel: false
    python_version: 3.8.13
    start_time: 1668047958.122701
    t:
      1:
      - 1
      - 5
      - 7
      - 11
      - 41
      - 49
      - 53
      - 55
      2:
      - 1
      - 5
      - 7
      - 11
      - 41
      - 49
      - 53
      - 55
      3:
      - 13
      - 16
      - 23
      - 24
      4: 3.8.13
      5: 0.13.5
      6: 4.23.1
      8:
      - 5
batch_size:
  desc: null
  value: 1024
epochs:
  desc: null
  value: 10
